language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
  - DJANGO=django==1.8.7
  - DJANGO=django==1.9
matrix:
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - pip install -e .[test]
before_script:
script: coverage run src/tests/manage.py test src/tests/test_historylinks/
after_script: coverage report
notifications:
  email: false
