language: python
sudo: false
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
  - DJANGO=django==1.7.11
  - DJANGO=django==1.8.7
  - DJANGO=django==1.9
matrix:
  fast_finish: true
  exclude:
    - python: 3.5
      env: DJANGO=django==1.7.11
    - python: 3.2
      env: DJANGO=django==1.9
    - python: 3.3
      env: DJANGO=django==1.9
install:
  - travis_retry pip install $DJANGO
  - pip install -e .[test]
before_script:
script: coverage run src/tests/manage.py test src/tests/test_historylinks/
after_script: coverage report
notifications:
  email: false
