language: python
sudo: false
python:
  - 3.8
  - 3.9
  - 3.10
cache:
  directories:
    - $HOME/.cache/pip
env:
  - DJANGO=django==3.2.16
  - DJANGO=django==4.1.4
matrix:
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - pip install -e .[test]
before_script:
script: coverage run src/tests/manage.py test src/tests/test_historylinks/
after_script: coverage report
notifications:
  email: false
