name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONDEVMODE: 1
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
        django-version:
          - '>=4.2,<4.3'
          - '>=4.1,<4.2'
          - '>=3.2,<4.0'
        exclude:
          - python-version: 3.7
            django-version: '>=4.1,<4.2'
          - python-version: 3.7
            django-version: '>=4.2,<4.3'
          - python-version: '3.10'
            django-version: '>=3.2,<4.0'
          - python-version: '3.11'
            django-version: '>=3.2,<4.0'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (Django ${{ matrix.django-version }})
      run: |
        python -m pip install --upgrade pip
        python -m pip install --pre django'${{ matrix.django-version }}'
        pip install -e .[test]
    - name: Test with unittest
      run: |
        coverage run src/tests/manage.py test src/tests/test_historylinks/
        coverage report
